
package pl.egu.agh.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentService", targetNamespace = "http://api.soa.agh.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentService {


    /**
     * 
     * @return
     *     returns pl.egu.agh.soa.GetAllStudentsResponse.Students
     */
    @WebMethod
    @WebResult(name = "students", targetNamespace = "")
    @RequestWrapper(localName = "getAllStudents", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetAllStudents")
    @ResponseWrapper(localName = "getAllStudentsResponse", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetAllStudentsResponse")
    public pl.egu.agh.soa.GetAllStudentsResponse.Students getAllStudents();

    /**
     * 
     * @param idx
     * @return
     *     returns pl.egu.agh.soa.GetStudentsCoursesResponse.Courses
     */
    @WebMethod
    @WebResult(name = "courses", targetNamespace = "")
    @RequestWrapper(localName = "getStudentsCourses", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentsCourses")
    @ResponseWrapper(localName = "getStudentsCoursesResponse", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentsCoursesResponse")
    public pl.egu.agh.soa.GetStudentsCoursesResponse.Courses getStudentsCourses(
        @WebParam(name = "idx", targetNamespace = "")
        int idx);

    /**
     * 
     * @param firstName
     * @param lastName
     * @param idx
     * @param age
     * @param faculty
     * @return
     *     returns pl.egu.agh.soa.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateStudent", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.UpdateStudent")
    @ResponseWrapper(localName = "updateStudentResponse", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.UpdateStudentResponse")
    public Student updateStudent(
        @WebParam(name = "idx", targetNamespace = "")
        int idx,
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "faculty", targetNamespace = "")
        String faculty);

    /**
     * 
     * @param firstName
     * @param lastName
     * @param idx
     * @param age
     * @param faculty
     * @return
     *     returns pl.egu.agh.soa.Student
     */
    @WebMethod
    @WebResult(name = "student", targetNamespace = "")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.AddStudentResponse")
    public Student addStudent(
        @WebParam(name = "idx", targetNamespace = "")
        int idx,
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "faculty", targetNamespace = "")
        String faculty);

    /**
     * 
     * @param age
     * @return
     *     returns pl.egu.agh.soa.GetStudentsByAgeResponse.Students
     */
    @WebMethod
    @WebResult(name = "students", targetNamespace = "")
    @RequestWrapper(localName = "getStudentsByAge", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentsByAge")
    @ResponseWrapper(localName = "getStudentsByAgeResponse", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentsByAgeResponse")
    public pl.egu.agh.soa.GetStudentsByAgeResponse.Students getStudentsByAge(
        @WebParam(name = "age", targetNamespace = "")
        int age);

    /**
     * 
     * @param firstName
     * @return
     *     returns pl.egu.agh.soa.GetStudentsByFirstNameResponse.Students
     */
    @WebMethod
    @WebResult(name = "students", targetNamespace = "")
    @RequestWrapper(localName = "getStudentsByFirstName", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentsByFirstName")
    @ResponseWrapper(localName = "getStudentsByFirstNameResponse", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentsByFirstNameResponse")
    public pl.egu.agh.soa.GetStudentsByFirstNameResponse.Students getStudentsByFirstName(
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName);

    /**
     * 
     * @param faculty
     * @return
     *     returns pl.egu.agh.soa.GetStudentsByFacultyResponse.Students
     */
    @WebMethod
    @WebResult(name = "students", targetNamespace = "")
    @RequestWrapper(localName = "getStudentsByFaculty", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentsByFaculty")
    @ResponseWrapper(localName = "getStudentsByFacultyResponse", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentsByFacultyResponse")
    public pl.egu.agh.soa.GetStudentsByFacultyResponse.Students getStudentsByFaculty(
        @WebParam(name = "faculty", targetNamespace = "")
        String faculty);

    /**
     * 
     * @param idx
     * @return
     *     returns pl.egu.agh.soa.Student
     */
    @WebMethod
    @WebResult(name = "student", targetNamespace = "")
    @RequestWrapper(localName = "getStudentByIdx", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentByIdx")
    @ResponseWrapper(localName = "getStudentByIdxResponse", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentByIdxResponse")
    public Student getStudentByIdx(
        @WebParam(name = "idx", targetNamespace = "")
        int idx);

    /**
     * 
     * @param lastName
     * @return
     *     returns pl.egu.agh.soa.GetStudentsByLastNameResponse.Students
     */
    @WebMethod
    @WebResult(name = "students", targetNamespace = "")
    @RequestWrapper(localName = "getStudentsByLastName", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentsByLastName")
    @ResponseWrapper(localName = "getStudentsByLastNameResponse", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetStudentsByLastNameResponse")
    public pl.egu.agh.soa.GetStudentsByLastNameResponse.Students getStudentsByLastName(
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName);

    /**
     * 
     * @param idx
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteStudent", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.DeleteStudent")
    @ResponseWrapper(localName = "deleteStudentResponse", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.DeleteStudentResponse")
    public boolean deleteStudent(
        @WebParam(name = "idx", targetNamespace = "")
        int idx);

    /**
     * 
     * @param idx
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBase64Avatar", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetBase64Avatar")
    @ResponseWrapper(localName = "getBase64AvatarResponse", targetNamespace = "http://api.soa.agh.edu.pl/", className = "pl.egu.agh.soa.GetBase64AvatarResponse")
    public String getBase64Avatar(
        @WebParam(name = "idx", targetNamespace = "")
        int idx);

}
