// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package pl.edu.agh.soa.models;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 idx = 1;</code>
     * @return The idx.
     */
    int getIdx();

    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string avatar_filepath = 4;</code>
     * @return The avatarFilepath.
     */
    java.lang.String getAvatarFilepath();
    /**
     * <code>string avatar_filepath = 4;</code>
     * @return The bytes for avatarFilepath.
     */
    com.google.protobuf.ByteString
        getAvatarFilepathBytes();

    /**
     * <code>int32 age = 5;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>repeated .Course courses = 6;</code>
     */
    java.util.List<StudentProto.Course> 
        getCoursesList();
    /**
     * <code>repeated .Course courses = 6;</code>
     */
    StudentProto.Course getCourses(int index);
    /**
     * <code>repeated .Course courses = 6;</code>
     */
    int getCoursesCount();
    /**
     * <code>repeated .Course courses = 6;</code>
     */
    java.util.List<? extends StudentProto.CourseOrBuilder> 
        getCoursesOrBuilderList();
    /**
     * <code>repeated .Course courses = 6;</code>
     */
    StudentProto.CourseOrBuilder getCoursesOrBuilder(
        int index);

    /**
     * <code>string faculty = 7;</code>
     * @return The faculty.
     */
    java.lang.String getFaculty();
    /**
     * <code>string faculty = 7;</code>
     * @return The bytes for faculty.
     */
    com.google.protobuf.ByteString
        getFacultyBytes();
  }
  /**
   * Protobuf type {@code Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      firstName_ = "";
      lastName_ = "";
      avatarFilepath_ = "";
      courses_ = java.util.Collections.emptyList();
      faculty_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              idx_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              avatarFilepath_ = s;
              break;
            }
            case 40: {

              age_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                courses_ = new java.util.ArrayList<StudentProto.Course>();
                mutable_bitField0_ |= 0x00000001;
              }
              courses_.add(
                  input.readMessage(StudentProto.Course.parser(), extensionRegistry));
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              faculty_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          courses_ = java.util.Collections.unmodifiableList(courses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StudentProto.internal_static_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StudentProto.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StudentProto.Student.class, StudentProto.Student.Builder.class);
    }

    public static final int IDX_FIELD_NUMBER = 1;
    private int idx_;
    /**
     * <code>int32 idx = 1;</code>
     * @return The idx.
     */
    public int getIdx() {
      return idx_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FILEPATH_FIELD_NUMBER = 4;
    private volatile java.lang.Object avatarFilepath_;
    /**
     * <code>string avatar_filepath = 4;</code>
     * @return The avatarFilepath.
     */
    public java.lang.String getAvatarFilepath() {
      java.lang.Object ref = avatarFilepath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatarFilepath_ = s;
        return s;
      }
    }
    /**
     * <code>string avatar_filepath = 4;</code>
     * @return The bytes for avatarFilepath.
     */
    public com.google.protobuf.ByteString
        getAvatarFilepathBytes() {
      java.lang.Object ref = avatarFilepath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatarFilepath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 5;
    private int age_;
    /**
     * <code>int32 age = 5;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }

    public static final int COURSES_FIELD_NUMBER = 6;
    private java.util.List<StudentProto.Course> courses_;
    /**
     * <code>repeated .Course courses = 6;</code>
     */
    public java.util.List<StudentProto.Course> getCoursesList() {
      return courses_;
    }
    /**
     * <code>repeated .Course courses = 6;</code>
     */
    public java.util.List<? extends StudentProto.CourseOrBuilder> 
        getCoursesOrBuilderList() {
      return courses_;
    }
    /**
     * <code>repeated .Course courses = 6;</code>
     */
    public int getCoursesCount() {
      return courses_.size();
    }
    /**
     * <code>repeated .Course courses = 6;</code>
     */
    public StudentProto.Course getCourses(int index) {
      return courses_.get(index);
    }
    /**
     * <code>repeated .Course courses = 6;</code>
     */
    public StudentProto.CourseOrBuilder getCoursesOrBuilder(
        int index) {
      return courses_.get(index);
    }

    public static final int FACULTY_FIELD_NUMBER = 7;
    private volatile java.lang.Object faculty_;
    /**
     * <code>string faculty = 7;</code>
     * @return The faculty.
     */
    public java.lang.String getFaculty() {
      java.lang.Object ref = faculty_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        faculty_ = s;
        return s;
      }
    }
    /**
     * <code>string faculty = 7;</code>
     * @return The bytes for faculty.
     */
    public com.google.protobuf.ByteString
        getFacultyBytes() {
      java.lang.Object ref = faculty_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        faculty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idx_ != 0) {
        output.writeInt32(1, idx_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (!getAvatarFilepathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, avatarFilepath_);
      }
      if (age_ != 0) {
        output.writeInt32(5, age_);
      }
      for (int i = 0; i < courses_.size(); i++) {
        output.writeMessage(6, courses_.get(i));
      }
      if (!getFacultyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, faculty_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idx_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, idx_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (!getAvatarFilepathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, avatarFilepath_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, age_);
      }
      for (int i = 0; i < courses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, courses_.get(i));
      }
      if (!getFacultyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, faculty_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StudentProto.Student)) {
        return super.equals(obj);
      }
      StudentProto.Student other = (StudentProto.Student) obj;

      if (getIdx()
          != other.getIdx()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getAvatarFilepath()
          .equals(other.getAvatarFilepath())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getCoursesList()
          .equals(other.getCoursesList())) return false;
      if (!getFaculty()
          .equals(other.getFaculty())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDX_FIELD_NUMBER;
      hash = (53 * hash) + getIdx();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + AVATAR_FILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getAvatarFilepath().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (getCoursesCount() > 0) {
        hash = (37 * hash) + COURSES_FIELD_NUMBER;
        hash = (53 * hash) + getCoursesList().hashCode();
      }
      hash = (37 * hash) + FACULTY_FIELD_NUMBER;
      hash = (53 * hash) + getFaculty().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StudentProto.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StudentProto.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StudentProto.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StudentProto.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StudentProto.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StudentProto.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StudentProto.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StudentProto.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StudentProto.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StudentProto.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StudentProto.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StudentProto.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StudentProto.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        StudentProto.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StudentProto.internal_static_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StudentProto.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StudentProto.Student.class, StudentProto.Student.Builder.class);
      }

      // Construct using StudentProto.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCoursesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idx_ = 0;

        firstName_ = "";

        lastName_ = "";

        avatarFilepath_ = "";

        age_ = 0;

        if (coursesBuilder_ == null) {
          courses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          coursesBuilder_.clear();
        }
        faculty_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StudentProto.internal_static_Student_descriptor;
      }

      @java.lang.Override
      public StudentProto.Student getDefaultInstanceForType() {
        return StudentProto.Student.getDefaultInstance();
      }

      @java.lang.Override
      public StudentProto.Student build() {
        StudentProto.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public StudentProto.Student buildPartial() {
        StudentProto.Student result = new StudentProto.Student(this);
        int from_bitField0_ = bitField0_;
        result.idx_ = idx_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.avatarFilepath_ = avatarFilepath_;
        result.age_ = age_;
        if (coursesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            courses_ = java.util.Collections.unmodifiableList(courses_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.courses_ = courses_;
        } else {
          result.courses_ = coursesBuilder_.build();
        }
        result.faculty_ = faculty_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StudentProto.Student) {
          return mergeFrom((StudentProto.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StudentProto.Student other) {
        if (other == StudentProto.Student.getDefaultInstance()) return this;
        if (other.getIdx() != 0) {
          setIdx(other.getIdx());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getAvatarFilepath().isEmpty()) {
          avatarFilepath_ = other.avatarFilepath_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (coursesBuilder_ == null) {
          if (!other.courses_.isEmpty()) {
            if (courses_.isEmpty()) {
              courses_ = other.courses_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCoursesIsMutable();
              courses_.addAll(other.courses_);
            }
            onChanged();
          }
        } else {
          if (!other.courses_.isEmpty()) {
            if (coursesBuilder_.isEmpty()) {
              coursesBuilder_.dispose();
              coursesBuilder_ = null;
              courses_ = other.courses_;
              bitField0_ = (bitField0_ & ~0x00000001);
              coursesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCoursesFieldBuilder() : null;
            } else {
              coursesBuilder_.addAllMessages(other.courses_);
            }
          }
        }
        if (!other.getFaculty().isEmpty()) {
          faculty_ = other.faculty_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StudentProto.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StudentProto.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int idx_ ;
      /**
       * <code>int32 idx = 1;</code>
       * @return The idx.
       */
      public int getIdx() {
        return idx_;
      }
      /**
       * <code>int32 idx = 1;</code>
       * @param value The idx to set.
       * @return This builder for chaining.
       */
      public Builder setIdx(int value) {
        
        idx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idx = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdx() {
        
        idx_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string first_name = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string last_name = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object avatarFilepath_ = "";
      /**
       * <code>string avatar_filepath = 4;</code>
       * @return The avatarFilepath.
       */
      public java.lang.String getAvatarFilepath() {
        java.lang.Object ref = avatarFilepath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatarFilepath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string avatar_filepath = 4;</code>
       * @return The bytes for avatarFilepath.
       */
      public com.google.protobuf.ByteString
          getAvatarFilepathBytes() {
        java.lang.Object ref = avatarFilepath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatarFilepath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string avatar_filepath = 4;</code>
       * @param value The avatarFilepath to set.
       * @return This builder for chaining.
       */
      public Builder setAvatarFilepath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatarFilepath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string avatar_filepath = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvatarFilepath() {
        
        avatarFilepath_ = getDefaultInstance().getAvatarFilepath();
        onChanged();
        return this;
      }
      /**
       * <code>string avatar_filepath = 4;</code>
       * @param value The bytes for avatarFilepath to set.
       * @return This builder for chaining.
       */
      public Builder setAvatarFilepathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatarFilepath_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 5;</code>
       * @return The age.
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 5;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<StudentProto.Course> courses_ =
        java.util.Collections.emptyList();
      private void ensureCoursesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          courses_ = new java.util.ArrayList<StudentProto.Course>(courses_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          StudentProto.Course, StudentProto.Course.Builder, StudentProto.CourseOrBuilder> coursesBuilder_;

      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public java.util.List<StudentProto.Course> getCoursesList() {
        if (coursesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(courses_);
        } else {
          return coursesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public int getCoursesCount() {
        if (coursesBuilder_ == null) {
          return courses_.size();
        } else {
          return coursesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public StudentProto.Course getCourses(int index) {
        if (coursesBuilder_ == null) {
          return courses_.get(index);
        } else {
          return coursesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public Builder setCourses(
          int index, StudentProto.Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.set(index, value);
          onChanged();
        } else {
          coursesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public Builder setCourses(
          int index, StudentProto.Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.set(index, builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public Builder addCourses(StudentProto.Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.add(value);
          onChanged();
        } else {
          coursesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public Builder addCourses(
          int index, StudentProto.Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.add(index, value);
          onChanged();
        } else {
          coursesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public Builder addCourses(
          StudentProto.Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.add(builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public Builder addCourses(
          int index, StudentProto.Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.add(index, builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public Builder addAllCourses(
          java.lang.Iterable<? extends StudentProto.Course> values) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, courses_);
          onChanged();
        } else {
          coursesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public Builder clearCourses() {
        if (coursesBuilder_ == null) {
          courses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          coursesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public Builder removeCourses(int index) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.remove(index);
          onChanged();
        } else {
          coursesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public StudentProto.Course.Builder getCoursesBuilder(
          int index) {
        return getCoursesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public StudentProto.CourseOrBuilder getCoursesOrBuilder(
          int index) {
        if (coursesBuilder_ == null) {
          return courses_.get(index);  } else {
          return coursesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public java.util.List<? extends StudentProto.CourseOrBuilder> 
           getCoursesOrBuilderList() {
        if (coursesBuilder_ != null) {
          return coursesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(courses_);
        }
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public StudentProto.Course.Builder addCoursesBuilder() {
        return getCoursesFieldBuilder().addBuilder(
            StudentProto.Course.getDefaultInstance());
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public StudentProto.Course.Builder addCoursesBuilder(
          int index) {
        return getCoursesFieldBuilder().addBuilder(
            index, StudentProto.Course.getDefaultInstance());
      }
      /**
       * <code>repeated .Course courses = 6;</code>
       */
      public java.util.List<StudentProto.Course.Builder> 
           getCoursesBuilderList() {
        return getCoursesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          StudentProto.Course, StudentProto.Course.Builder, StudentProto.CourseOrBuilder> 
          getCoursesFieldBuilder() {
        if (coursesBuilder_ == null) {
          coursesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              StudentProto.Course, StudentProto.Course.Builder, StudentProto.CourseOrBuilder>(
                  courses_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          courses_ = null;
        }
        return coursesBuilder_;
      }

      private java.lang.Object faculty_ = "";
      /**
       * <code>string faculty = 7;</code>
       * @return The faculty.
       */
      public java.lang.String getFaculty() {
        java.lang.Object ref = faculty_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          faculty_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string faculty = 7;</code>
       * @return The bytes for faculty.
       */
      public com.google.protobuf.ByteString
          getFacultyBytes() {
        java.lang.Object ref = faculty_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          faculty_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string faculty = 7;</code>
       * @param value The faculty to set.
       * @return This builder for chaining.
       */
      public Builder setFaculty(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        faculty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string faculty = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFaculty() {
        
        faculty_ = getDefaultInstance().getFaculty();
        onChanged();
        return this;
      }
      /**
       * <code>string faculty = 7;</code>
       * @param value The bytes for faculty to set.
       * @return This builder for chaining.
       */
      public Builder setFacultyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        faculty_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final StudentProto.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StudentProto.Student();
    }

    public static StudentProto.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public StudentProto.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CourseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Course)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 ects = 2;</code>
     * @return The ects.
     */
    int getEcts();
  }
  /**
   * Protobuf type {@code Course}
   */
  public  static final class Course extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Course)
      CourseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Course.newBuilder() to construct.
    private Course(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Course() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Course();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Course(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              ects_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StudentProto.internal_static_Course_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StudentProto.internal_static_Course_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StudentProto.Course.class, StudentProto.Course.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ECTS_FIELD_NUMBER = 2;
    private int ects_;
    /**
     * <code>int32 ects = 2;</code>
     * @return The ects.
     */
    public int getEcts() {
      return ects_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (ects_ != 0) {
        output.writeInt32(2, ects_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (ects_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ects_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StudentProto.Course)) {
        return super.equals(obj);
      }
      StudentProto.Course other = (StudentProto.Course) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getEcts()
          != other.getEcts()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ECTS_FIELD_NUMBER;
      hash = (53 * hash) + getEcts();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StudentProto.Course parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StudentProto.Course parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StudentProto.Course parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StudentProto.Course parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StudentProto.Course parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StudentProto.Course parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StudentProto.Course parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StudentProto.Course parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StudentProto.Course parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StudentProto.Course parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StudentProto.Course parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StudentProto.Course parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StudentProto.Course prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Course}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Course)
        StudentProto.CourseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StudentProto.internal_static_Course_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StudentProto.internal_static_Course_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StudentProto.Course.class, StudentProto.Course.Builder.class);
      }

      // Construct using StudentProto.Course.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        ects_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StudentProto.internal_static_Course_descriptor;
      }

      @java.lang.Override
      public StudentProto.Course getDefaultInstanceForType() {
        return StudentProto.Course.getDefaultInstance();
      }

      @java.lang.Override
      public StudentProto.Course build() {
        StudentProto.Course result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public StudentProto.Course buildPartial() {
        StudentProto.Course result = new StudentProto.Course(this);
        result.name_ = name_;
        result.ects_ = ects_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StudentProto.Course) {
          return mergeFrom((StudentProto.Course)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StudentProto.Course other) {
        if (other == StudentProto.Course.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getEcts() != 0) {
          setEcts(other.getEcts());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StudentProto.Course parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StudentProto.Course) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int ects_ ;
      /**
       * <code>int32 ects = 2;</code>
       * @return The ects.
       */
      public int getEcts() {
        return ects_;
      }
      /**
       * <code>int32 ects = 2;</code>
       * @param value The ects to set.
       * @return This builder for chaining.
       */
      public Builder setEcts(int value) {
        
        ects_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ects = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEcts() {
        
        ects_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Course)
    }

    // @@protoc_insertion_point(class_scope:Course)
    private static final StudentProto.Course DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StudentProto.Course();
    }

    public static StudentProto.Course getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Course>
        PARSER = new com.google.protobuf.AbstractParser<Course>() {
      @java.lang.Override
      public Course parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Course(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Course> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Course> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public StudentProto.Course getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Course_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Course_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\"\216\001\n\007Student\022\013\n\003idx\030\001 \001(\005" +
      "\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tlast_name\030\003 \001(\t\022" +
      "\027\n\017avatar_filepath\030\004 \001(\t\022\013\n\003age\030\005 \001(\005\022\030\n" +
      "\007courses\030\006 \003(\0132\007.Course\022\017\n\007faculty\030\007 \001(\t" +
      "\"$\n\006Course\022\014\n\004name\030\001 \001(\t\022\014\n\004ects\030\002 \001(\005B\016" +
      "B\014StudentProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "Idx", "FirstName", "LastName", "AvatarFilepath", "Age", "Courses", "Faculty", });
    internal_static_Course_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Course_descriptor,
        new java.lang.String[] { "Name", "Ects", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
